---
name: List Devices Test

# 📜 https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  greet:
    name: Find Device ID
    runs-on: macos-15
    steps:
      - name: Find iOS 18.5, iPhone 16
        run: |
          curl \
            --silent \
            --show-error \
            --location https://raw.githubusercontent.com/dirtyhenry/swift-blocks/main/Scripts/ListDevices.swift \
            -o listDevices
          chmod +x listDevices
          DEVICE_ID=$(./listDevices "iOS 18.5" "iPhone 16")
          echo "The output of the script was $DEVICE_ID"
          echo "All available devices are:"
          xcrun simctl list devices available
